name: scrape

on:
  schedule:
    - cron: "0 * * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run scraper
        run: python scraper.py

      - name: Debug list files
        run: |
          echo "===== 当前目录 ====="
          pwd
          echo "===== 文件列表 ====="
          ls -la

      - name: Commit update
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

          if [ -f data.json ]; then
            git add -f data.json
            git status
            git commit -m "Auto update deals [skip ci]" || echo "No changes"
            git push
          else
            echo "❌ data.json not found!"
          fi
